import type { PageReport, IssueData } from './types';

const ICON = { high: '🔴', medium: '🟡', low: '🟢' };
const SEVERITY_LABEL = { high: 'High', medium: 'Medium', low: 'Low' };
const REASON_LABEL: Record<string, string> = {
  'props': 'Props change',
  'state': 'State change',
  'context': 'Context change',
};

function fmtTime(ms: number | null): string {
  if (ms == null) return 'N/A';
  return `${ms.toFixed(1)} ms`;
}

function fmtFps(fps: number | null): string {
  if (fps == null) return 'N/A';
  const flag = fps < 30 ? ' ⚠️' : fps < 60 ? ' ⚡' : '';
  return `${Math.round(fps)} fps${flag}`;
}

function fmtReasons(reasons: string[]): string {
  return reasons.map(r => {
    const [type, ...rest] = r.split(':');
    const label = REASON_LABEL[type] ?? type;
    const name = rest.join(':');
    return name ? `\`${label}: ${name}\`` : `\`${label}\``;
  }).join(', ') || 'unknown';
}

function buildChangesTable(issue: IssueData): string {
  if (!issue.changes || issue.changes.length === 0) return '';

  const rows = issue.changes.slice(0, 5).map(c => {
    const prev = c.prevValue ?? '—';
    const curr = c.value ?? '—';
    return `| \`${c.type}\` | \`${c.name}\` | \`${prev}\` | \`${curr}\` |`;
  });

  return `
**Change details** (last snapshot, up to 5 entries)

| Type | Name | Previous value | Current value |
|------|------|---------------|---------------|
${rows.join('\n')}
`;
}

function getSuggestion(issue: IssueData): string {
  const lines: string[] = [];
  const reasons = issue.reasons;

  if (reasons.some(r => r.startsWith('props'))) {
    lines.push(
      '- Wrap with `React.memo()` to skip re-renders when props are shallowly equal',
      '- Stabilize reference props: `useMemo` for objects/arrays, `useCallback` for functions',
    );
  }
  if (reasons.some(r => r.startsWith('context'))) {
    lines.push(
      '- Context value object is recreated on every parent render — add `useMemo`',
      '- Split large contexts into smaller ones so only affected consumers re-render',
    );
  }
  if (reasons.some(r => r.startsWith('state'))) {
    lines.push(
      '- High-frequency state updates (timers, WebSocket) — throttle/debounce to ≥200 ms',
      '- Batch related state with `useReducer` to avoid cascading renders',
    );
  }
  if (issue.unnecessaryCount > 0) {
    const pct = Math.round((issue.unnecessaryCount / issue.count) * 100);
    lines.push(`- **${pct}% of renders were unnecessary** — component re-rendered with identical props/state`);
    lines.push('- Add `React.memo()` or fix unstable references in the parent');
  }
  if (issue.avgTime != null && issue.avgTime > 16) {
    lines.push(`- Avg render time ${issue.avgTime} ms exceeds 16 ms budget — profile with React DevTools Profiler`);
  }
  if (issue.minFps != null && issue.minFps < 60) {
    lines.push(`- FPS dropped to ${Math.round(issue.minFps)} — consider moving heavy work to a Web Worker or virtualizing long lists`);
  }

  if (lines.length === 0) {
    lines.push('- Open React DevTools Profiler → record → check "Why did this render?"');
  }

  return lines.join('\n');
}

export function buildIssueBody(report: PageReport, projectName: string): string {
  return `<!-- page-url: ${report.url} -->
<!-- project: ${projectName} -->

## Page Info

| Project | Page | URL | Detected at | Observe duration |
|---------|------|-----|-------------|-----------------|
| \`${projectName}\` | ${report.page} | \`${report.url}\` | ${new Date(report.timestamp).toUTCString()} | ${report.observeDuration / 1000}s |

## Problematic Components

${report.issues.map((issue, idx) => `
### ${idx + 1}. ${ICON[issue.severity]} \`${issue.component}\`

| Metric | Value |
|--------|-------|
| Re-renders | **${issue.count}** |
| Severity | ${SEVERITY_LABEL[issue.severity]} |
| Avg render time | ${fmtTime(issue.avgTime)} |
| Min FPS during renders | ${fmtFps(issue.minFps)} |
| Unnecessary renders | ${issue.unnecessaryCount} (${issue.count > 0 ? Math.round(issue.unnecessaryCount / issue.count * 100) : 0}%) |
| Triggered by | ${fmtReasons(issue.reasons)} |
${buildChangesTable(issue)}
**Suggestions**

${getSuggestion(issue)}
`).join('\n---\n')}

## Screenshot

<img src="data:image/png;base64,${report.screenshotBase64}" width="800" alt="page screenshot" />

## Reproduction

1. Visit \`${report.url}\`
2. Wait for the page to fully load (~${report.observeDuration / 1000}s)
3. Open React DevTools → Profiler → check "Record why each component rendered" → record
4. Interact with the page, then stop recording — check the components listed above

---
*Generated by [react-scan-cli](https://github.com/Tzyito/react-scan-cli) · Close this issue once fixed*`.trim();
}
